baseURL = "https://www.martinescu.com/"
languageCode = "en-us"
title = "Petrica Martinescu - Engineer, Solution Architect"
theme = "hugo-coder"
googleAnalytics = "UA-1491698-2"
disqusShortname = "martinescu"
canonifyurls = true

[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Petrică Martinescu"
    info = "Engineer"
    avatarurl = "images/petrica-martinescu.jpg"

    hidecredits = true
    hidecopyright = true

    colorscheme = "light"

    favicon_32 = false
    favicon_16 = false

    customCSS = ["css/style.css"]

# Social links
[[params.social]]
    name = "Github"
    weight = 1
    icon = "fa fa-github"
    url = "https://github.com/petrica/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/martinescu/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/petrica-martinescu"

[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            #[[languages.en.menu.main]]
            #name = "About"
            #weight = 1
            #url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            #[[languages.en.menu.main]]
            #name = "Projects"
            #weight = 3
            #url = "projects/"

            # [[languages.en.menu.main]]
            # name = "Contact me"
            # weight = 5
            # url = "contact/"