baseURL = "https://www.martinescu.com/"
languageCode = "en-us"
title = "Martinescu"
theme = "hugo-coder"

[params]
    author = "Petrică Martinescu"
    info = "Engineer"
    avatarurl = "images/petrica-martinescu.jpg"

    hidecredits = true
    hidecopyright = true

    colorscheme = "dark"

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/petrica/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/martinescu/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/petrica-martinescu"